### ISSUE TITLE
Why are tests etc. in framework?

### ISSUE THREAD

**Issue by ssteinerx** [pybee/Python-Apple-support#8] opened 2016-11-27 15:18 UTC
There seems to be a whole lot of non-runtime type stuff in the frameworks.

E.G. the python/include directory is in there as is lib/pythonx.x/test directory.

I apologize if I missed it, but is there a command/script/makefile target etc. to make a slim runtime-only version of the frameworks?

Thanks, ssteinerX

**Comment by freakboy3742** [comment] 2016-11-27 15:33
Thanks for the report - this looks like duplicate of #4. It was an oversight of the most recent build that I published; when I get a chance I'll publish an updated build that should strip the test directory out again.

**Closed by freakboy3742** 2016-11-27 15:33 UTC

**Comment by ssteinerx** [comment] 2016-11-27 22:08
@freakboy3742 Sorry about that, not sure what-all should be left after the build, will check back after the next release.
