### ISSUE TITLE
unknow? ???

### ISSUE THREAD

**Issue by hatjs880328s** [pybee/Python-Apple-support#63] opened 2018-12-11 09:20 UTC
$ make iOS to build everything for iOS.
# Unpack sources
mkdir -p build/iOS/bzip2-1.0.6-iphonesimulator.x86_64
tar zxf downloads/bzip2-1.0.6.tgz --strip-components 1 -C build/iOS/bzip2-1.0.6-iphonesimulator.x86_64
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
make: *** [build/iOS/bzip2-1.0.6-iphonesimulator.x86_64/Makefile] Error 1

**Comment by hatjs880328s** [comment] 2018-12-11 09:25
/Users/shanwz/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SwiftLintXcode.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/shanwz/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SwiftLintXcode.xcplugin/Contents/MacOS/SwiftLintXcode): no suitable image found.  Did find:

**Comment by freakboy3742** [comment] 2018-12-11 23:03
Although the error message doesn't make this obvious, it's a duplicate of #53 - bzip is currently in hosting limbo, and we're waiting for an statement on the "new" official location.

**Closed by freakboy3742** 2018-12-11 23:03 UTC
